# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RI_9sFXAxNkKoQlD2FFRsb5GB00ccTW9
"""

import math
import numpy as np
from numpy.random import randn
from statsmodels.stats.weightstats import ztest
from statsmodels.stats import weightstats as stests
import pandas as pd

mean_iq = 153
sd_iq = 15/math.sqrt(50)
null_mean =95
data = sd_iq*randn(50)+mean_iq
# print mean and sd
print('mean=%.2f stdv=%.2f' % (np.mean(data), np.std(data)))

ztest_Score, p_value= ztest(data,value = null_mean, alternative='larger')
if(p_value <  0.05):
  print("Reject Null Hypothesis")
else:
  print("Fail to Reject NUll Hypothesis")

df = pd.read_csv('/content/sample_data/california_housing_test.csv')
df.head()

ztest ,propability_value = stests.ztest(df['population'], x2=None, value=146)
print("Z-Score value:",ztest,"p value:",float(propability_value))
if(propability_value <  0.05):
  print("Reject Null Hypothesis")
else:
  print("Fail to Reject NUll Hypothesis")

ztest ,propability_value = stests.ztest(df['median_income'], x2=None, value=146)
print("Z-Score value:",ztest,"p value:",float(propability_value))
if(propability_value <  0.05):
  print("Reject Null Hypothesis")
else:
  print("Fail to Reject NUll Hypothesis")

ztest ,propability_value = stests.ztest(df['population'], df['median_income'], value=146)
print("Z-Score value:",ztest,"p value:",float(propability_value))
if(propability_value <  0.05):
  print("Reject Null Hypothesis")
else:
  print("Fail to Reject NUll Hypothesis")